package com.openx.model.video;
/* loaded from: classes3.dex */
public class VideoAdEvent {

    /* loaded from: classes3.dex */
    public enum Event {
        AD_IMPRESSION,
        AD_CREATIVEVIEW,
        AD_START,
        AD_FIRSTQUARTILE,
        AD_MIDPOINT,
        AD_THIRDQUARTILE,
        AD_COMPLETE,
        AD_MUTE,
        AD_UNMUTE,
        AD_PAUSE,
        AD_REWIND,
        AD_RESUME,
        AD_FULLSCREEN,
        AD_EXITFULLSCREEN,
        AD_EXPAND,
        AD_COLLAPSE,
        AD_ACCEPTINVITATION,
        AD_ACCEPTINVITATIONLINEAR,
        AD_CLOSELINEAR,
        AD_CLOSE,
        AD_SKIP,
        AD_PROGRESS,
        AD_PREPARING,
        AD_PREPARED,
        CONTENT_PREPARING,
        CONTENT_PREPARED,
        CONTENT_START,
        CONTENT_COMPLETE,
        CONTENT_MUTE,
        CONTENT_UNMUTE,
        CONTENT_PAUSE,
        CONTENT_REWIND,
        CONTENT_RESUME,
        CONTENT_FULLSCREEN,
        CONTENT_EXITFULLSCREEN,
        CONTENT_PLAYLIST_COMPLETE,
        CONTENT_CLOSE,
        AD_WINDOW_HAS_FOCUS,
        AD_WINDOW_HAS_NO_FOCUS,
        CONTENT_WINDOW_HAS_FOCUS,
        CONTENT_WINDOW_HAS_NO_FOCUS,
        TOUCH
    }
}
